<?php

declare(strict_types=1);

namespace ThinkEncryption\tests\service;

use ThinkEncryption\exception\EncryptException;
use ThinkEncryption\service\encrypt\AES;
use ThinkEncryption\tests\TestCaseBase;

class AESTest extends TestCaseBase
{
    private AES $aes;
    private string $testKey;
    private string $testIv;

    protected function setUp(): void
    {
        parent::setUp();

        $this->aes = new AES();
        $this->testKey = $this->generateRandomString(32);
        $this->testIv = $this->generateRandomString(16);
    }

    public function testEncryptDecryptString(): void
    {
        $plaintext = 'Hello, World! 你好世界！';
        $encrypted = $this->aes->encrypt($plaintext, $this->testKey, $this->testIv);
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey);

        $this->assertEquals($plaintext, $decrypted);
    }

    public function testEncryptDecryptArray(): void
    {
        $data = [
            'name' => '测试用户',
            'age' => 25,
            'email' => 'test@example.com',
            'nested' => [
                'key' => 'value',
                'number' => 123,
            ],
        ];

        $encrypted = $this->aes->encrypt($data, $this->testKey, $this->testIv);
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey);

        $this->assertEquals($data, $decrypted);
    }

    public function testEncryptDecryptInteger(): void
    {
        $data = 42;
        $encrypted = $this->aes->encrypt($data, $this->testKey, $this->testIv);
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey);

        $this->assertEquals($data, $decrypted);
    }

    public function testEncryptDecryptNull(): void
    {
        $data = null;
        $encrypted = $this->aes->encrypt($data, $this->testKey, $this->testIv);
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey);

        $this->assertNull($decrypted);
    }

    public function testEncryptWithAutoGeneratedIv(): void
    {
        $data = 'Test data with auto IV';
        $encrypted = $this->aes->encrypt($data, $this->testKey);
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey);

        $this->assertEquals($data, $decrypted);
    }

    public function testEncryptedOutputIsDifferentEachTime(): void
    {
        $data = 'Same data';
        $encrypted1 = $this->aes->encrypt($data, $this->testKey);
        $encrypted2 = $this->aes->encrypt($data, $this->testKey);

        // 由于 IV 不同，密文应该不同
        $this->assertNotEquals($encrypted1, $encrypted2);

        // 但解密后应该相同
        $this->assertEquals($data, $this->aes->decrypt($encrypted1, $this->testKey));
        $this->assertEquals($data, $this->aes->decrypt($encrypted2, $this->testKey));
    }

    public function testKeyShorterThan32CharsIsHashed(): void
    {
        $shortKey = 'my-short-key-1234567890'; // 24 chars
        $data = 'Test data';

        $encrypted = $this->aes->encrypt($data, $shortKey);
        $decrypted = $this->aes->decrypt($encrypted, $shortKey);

        $this->assertEquals($data, $decrypted);
    }

    public function testKeyLongerThan32CharsIsTruncated(): void
    {
        $longKey = $this->generateRandomString(64); // 64 chars
        $data = 'Test data';

        $encrypted = $this->aes->encrypt($data, $longKey);
        $decrypted = $this->aes->decrypt($encrypted, $longKey);

        $this->assertEquals($data, $decrypted);
    }

    public function testDecryptWithWrongKeyFails(): void
    {
        $data = 'Secret data';
        $encrypted = $this->aes->encrypt($data, $this->testKey);
        $wrongKey = $this->generateRandomString(32);

        $this->expectException(EncryptException::class);
        $this->aes->decrypt($encrypted, $wrongKey);
    }

    public function testDecryptWithInvalidBase64(): void
    {
        $this->expectException(EncryptException::class);
        $this->aes->decrypt('not-valid-base64!!!', $this->testKey);
    }

    public function testDecryptWithEmptyData(): void
    {
        $this->expectException(EncryptException::class);
        $this->aes->decrypt('', $this->testKey);
    }

    public function testIvLengthMismatch(): void
    {
        $shortIv = 'short';
        $this->expectException(EncryptException::class);
        $this->aes->encrypt('data', $this->testKey, $shortIv);
    }

    public function testDecryptIvLengthMismatch(): void
    {
        $data = 'Test data';
        $encrypted = $this->aes->encrypt($data, $this->testKey);

        $this->expectException(EncryptException::class);
        $this->aes->decrypt($encrypted, $this->testKey, 'short-iv!!');
    }

    public function testCorruptedCiphertext(): void
    {
        $data = 'Test data';
        $encrypted = $this->aes->encrypt($data, $this->testKey);

        // 破坏密文
        $decoded = base64_decode($encrypted);
        $decoded[0] = chr(ord($decoded[0]) ^ 0xFF);
        $corrupted = base64_encode($decoded);

        $this->expectException(EncryptException::class);
        $this->aes->decrypt($corrupted, $this->testKey);
    }

    public function testKeyWithEnvFallback(): void
    {
        $originalValue = env('ENCRYPTION_KEY');
        try {
            // 设置环境变量
            putenv('ENCRYPTION_KEY=env_test_key_32_chars_here');

            $aes = new AES();
            $data = 'Test with env key';
            $encrypted = $aes->encrypt($data);

            // 解密时也使用环境变量
            $decrypted = $aes->decrypt($encrypted);

            $this->assertEquals($data, $decrypted);
        } finally {
            // 恢复环境变量
            if ($originalValue !== null) {
                putenv("ENCRYPTION_KEY={$originalValue}");
            } else {
                putenv('ENCRYPTION_KEY');
            }
        }
    }
}
