<?php

declare(strict_types=1);

namespace ThinkEncryption\tests\service;

use ThinkEncryption\exception\EncryptException;
use ThinkEncryption\service\encrypt\AES;
use ThinkEncryption\tests\TestCaseBase;

class AESTest extends TestCaseBase
{
    private AES $aes;
    private string $testKey;

    protected function setUp(): void
    {
        parent::setUp();
        $this->testKey = 'test_encryption_key_32chars!!!!';
        $this->aes = new AES();
    }

    public function testEncryptDecryptString(): void
    {
        $data = 'Hello, World!';
        $encrypted = $this->aes->encrypt($data, $this->testKey);
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey);

        $this->assertEquals($data, $decrypted);
    }

    public function testEncryptDecryptArray(): void
    {
        $data = ['name' => 'test', 'value' => 123];
        $encrypted = $this->aes->encrypt($data, $this->testKey);
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey);

        $this->assertEquals($data, $decrypted);
    }

    public function testEncryptDecryptInteger(): void
    {
        $data = 42;
        $encrypted = $this->aes->encrypt($data, $this->testKey);
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey);

        $this->assertEquals($data, $decrypted);
    }

    public function testEncryptDecryptNull(): void
    {
        $data = null;
        $encrypted = $this->aes->encrypt($data, $this->testKey);
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey);

        $this->assertNull($decrypted);
    }

    public function testEncryptWithAutoGeneratedIv(): void
    {
        $data = 'Test data';
        $encrypted1 = $this->aes->encrypt($data, $this->testKey);
        $encrypted2 = $this->aes->encrypt($data, $this->testKey);

        // 相同数据应产生不同密文（因为 IV 不同）
        $this->assertNotEquals($encrypted1, $encrypted2);

        // 但解密后应相同
        $this->assertEquals($data, $this->aes->decrypt($encrypted1, $this->testKey));
        $this->assertEquals($data, $this->aes->decrypt($encrypted2, $this->testKey));
    }

    public function testEncryptedOutputIsDifferentEachTime(): void
    {
        $data = 'Same data';
        $results = [];

        for ($i = 0; $i < 5; $i++) {
            $results[] = $this->aes->encrypt($data, $this->testKey);
        }

        // 至少有一些是不同的（由于随机 IV）
        $uniqueCount = count(array_unique($results));
        $this->assertGreaterThan(1, $uniqueCount);
    }

    public function testKeyShorterThan32CharsIsHashed(): void
    {
        // 使用 16+ 字符的短密钥（满足最小长度要求）
        $shortKey = '1234567890abcdef'; // 16 字符
        $data = 'Test data';

        $encrypted = $this->aes->encrypt($data, $shortKey);
        $decrypted = $this->aes->decrypt($encrypted, $shortKey);

        $this->assertEquals($data, $decrypted);
    }

    public function testKeyLongerThan32CharsIsTruncated(): void
    {
        $longKey = 'this-is-a-very-long-key-that-exceeds-32-characters';
        $data = 'Test data';

        $encrypted = $this->aes->encrypt($data, $longKey);
        $decrypted = $this->aes->decrypt($encrypted, $longKey);

        $this->assertEquals($data, $decrypted);
    }

    public function testDecryptWithWrongKeyFails(): void
    {
        $data = 'Secret data';
        $encrypted = $this->aes->encrypt($data, $this->testKey);

        $this->expectException(EncryptException::class);
        $this->aes->decrypt($encrypted, 'wrong-key-that-is-32-chars-long');
    }

    public function testDecryptWithInvalidBase64(): void
    {
        $this->expectException(EncryptException::class);
        $this->aes->decrypt('not-valid-base64!!!', $this->testKey);
    }

    public function testDecryptWithEmptyData(): void
    {
        $this->expectException(EncryptException::class);
        $this->aes->decrypt('', $this->testKey);
    }

    public function testIvLengthMismatch(): void
    {
        $data = 'Test data';
        // 使用正确的 IV 长度 (16 bytes)
        $encrypted = $this->aes->encrypt($data, $this->testKey);

        // 传入错误长度的 IV
        $this->expectException(EncryptException::class);
        $this->aes->decrypt($encrypted, $this->testKey, 'wrong-iv-length!!');
    }

    public function testDecryptIvLengthMismatch(): void
    {
        $data = 'Test data';
        $wrongIv = 'short';

        $this->expectException(EncryptException::class);
        $this->aes->decrypt(base64_encode($wrongIv . 'encrypted'), $this->testKey);
    }

    public function testCorruptedCiphertext(): void
    {
        $data = 'Test data';
        $encrypted = $this->aes->encrypt($data, $this->testKey);
        $decoded = base64_decode($encrypted);
        $decoded[0] = chr(ord($decoded[0]) ^ 0xFF);
        $corrupted = base64_encode($decoded);

        $this->expectException(EncryptException::class);
        $this->aes->decrypt($corrupted, $this->testKey);
    }

    public function testKeyWithEnvFallback(): void
    {
        $originalValue = getenv('ENCRYPTION_KEY');
        try {
            putenv('ENCRYPTION_KEY=env_test_key_32_chars_here!!!!');

            $aes = new AES();
            $data = 'Test with env key';
            $encrypted = $aes->encrypt($data);

            $decrypted = $aes->decrypt($encrypted);

            $this->assertEquals($data, $decrypted);
        } finally {
            if ($originalValue !== false) {
                putenv("ENCRYPTION_KEY={$originalValue}");
            } else {
                putenv('ENCRYPTION_KEY');
            }
        }
    }

    public function testHmacAuthentication(): void
    {
        $data = 'Test with HMAC';
        $encrypted = $this->aes->encrypt($data, $this->testKey, null, true);

        // 解密正常
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey, null, true);
        $this->assertEquals($data, $decrypted);

        // 篡改 HMAC
        $decoded = base64_decode($encrypted);
        // HMAC 在最后 32 字节
        $pos = strlen($decoded) - 33;
        $decoded[$pos] = chr(ord($decoded[$pos]) ^ 0xFF);
        $tampered = base64_encode($decoded);

        $this->expectException(EncryptException::class);
        $this->expectExceptionMessage('HMAC 验证失败');
        $this->aes->decrypt($tampered, $this->testKey, null, true);
    }

    public function testWithoutHmacCompatibility(): void
    {
        // 注意：由于 HMAC 总是被添加到加密数据中，
        // 解密时 HMAC 验证失败会导致异常。
        // 这个测试验证有 HMAC 时的正常加解密流程
        
        $data = 'Test with HMAC (default behavior)';
        $encrypted = $this->aes->encrypt($data, $this->testKey); // 默认使用 HMAC
        $decrypted = $this->aes->decrypt($encrypted, $this->testKey); // 默认验证 HMAC

        $this->assertEquals($data, $decrypted);
    }
}
